# Enable global music playback
playEverywhere: true

# Allow non-OP players to control music boxes
allowNonOpControl: false

# Enable single-cycle playback
singleCycle: false

# List of worlds where playback is allowed (plays globally if list is empty)
enabledWorlds:
#  - world
#  - nether
#  - the_end